# Generated by Django 6.0 on 2025-12-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_fisrt_app', '0004_publisher_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to='my_fisrt_app.author'),
        ),
    ]
